### PR TITLE
fix(net/ghttp): server shutdown not graceful using admin api `/debug/admin/shutdown`

### LINKED ISSUE #3358: net/ghttp: /debug/admin/shutdown is not graceful shutdown
```go
group.GET("/hello", func(r *ghttp.Request) {
					r.Response.Write("1")
					time.Sleep(10 * time.Second)
					r.Response.Write("ohell")
				})
```

**What version of `Go` and system type/arch are you using?**
go version go1.22.0 darwin/arm64

**What version of `GoFrame` are you using?**
github.com/gogf/gf/v2 v2.6.4

**Can this bug be re-produced with the latest release?**

**What did you do?**

**What did you expect to see?**
不知道为啥shutdown无法平滑关闭服务。导致业务数据丢失

**What did you see instead?**

### PR DESCRIPTION
**Pull request by gqcn**
fixed #3358

### CODE REVIEW

File: net/ghttp/ghttp_server_config_mess.go [hunk 1]
```diff
@@ -27,17 +27,34 @@ func (s *Server) SetFormParsingMemory(maxMemory int64) {
...
+func (s *Server) GetGraceful() bool {
+	return s.config.Graceful
 }
 
-// SetOpenApiPath sets the OpenApiPath for server.
-func (s *Server) SetOpenApiPath(path string) {
-	s.config.OpenApiPath = path
+// SetGracefulTimeout sets the GracefulTimeout for server.
+func (s *Server) SetGracefulTimeout(gracefulTimeout int) {
+	s.config.GracefulTimeout = gracefulTimeout
```
Comment (houseme) [inline net/ghttp/ghttp_server_config_mess.go:44]: 类型不匹配，结构体中uint8

**Review by wln32 — APPROVED** [review]

**Review by houseme — APPROVED** [review]

**Review by oldme-git — APPROVED** [review]
