### PR TITLE
fix(os/gtime): fix gtime.Value() when time only, add `time only` example

### LINKED ISSUE #2012: 插入 MySQL time 类型的字段，sql语句是 0000-01-01 H:i:s，诱发 Error: year is not in the range [1, 9999]
1. ### ENV

   go version ：go 1.18 windows/amd64

   GoFrame Version : v2.1.1

   Mysql : 5.7

   Mysql Drivers : v2.1.0

2. ###  Can this issue be re-produced with the latest release?
     yes

3. ### What did you do?

     在 MySQL表里，我创建了`time`类型的字段：

     ```mysql
     CREATE TABLE `c_table` (
         ...
       `begin_at` time DEFAULT NULL,
         ...
     );
     ```

     `gf gen dao`生成的`package do`结构体：

     ```go
     type CTable struct {
     	g.Meta        `orm:"table:c_table, do:true"`
         ...
     	BeginAt       *gtime.Time  
         ...
     }
     ```

     

     我在新增数据时，像这样操作，出现了问题：

     ```go
     func Add(ctx context.Context) (err error, data any) (err error){
         var m = dao.CTable.Ctx(ctx)
         ...
         
         beginAt := "14:39:51"
         
         m.Insert(do.CTable{
             ...
             BeginAt : gtime.New(beginAt),
             ...
         })
         return
     }
     ```

     我得到这样的 sql 语句，以及 error

     ```mysql
     INSERT INTO `c_table`(`begin_at`...) VALUES(...'0000-01-01 14:39:51') 
     Error: year is not in the range [1, 9999]: 0
     ```

     
     
     我顺便测试了下，修改年份，MySQL可以插入
     
     ```mysql
     INSERT INTO `c_table`(`begin_at`...) VALUES(...'0001-01-01 14:39:51') 
     ```
     
     
     
     为了规避这个问题，我强行把 `do.CTable.BeginAt` 类型修改成了空接口
     
     ```go
     type CTable struct {
     	g.Meta        `orm:"table:c_table, do:true"`
         ...
         BeginAt       any
         ...
     }
     ```
     
     插入数据时，存入手动转换的字符串：
     
     ```go
     func Add(ctx context.Context) (err error, data any) (err error){
         var m = dao.CTable.Ctx(ctx)
         ...
         
         datetime := "2022-07-15 15:16:14"
         
         m.Insert(do.CTable{
             ...
             BeginAt : gtime.New(datetime).Layout("15:04:05"),
             ...
         })
         return
     }
     ```
     
     虽然可以跑，但我觉得不应该修改 `package do`的内容，也不优雅..

### PR DESCRIPTION
**Pull request by niluan304**
#### add only time case for `func (t *Time) Value() (driver.Value, error)`:
```go
// Value is the interface providing the Value method for package database/sql/driver
// for retrieving value from golang variable to database.
func (t *Time) Value() (driver.Value, error) {
	if t == nil {
		return nil, nil
	}
	if t.IsZero() {
		return nil, nil
	}

	if t.Year() == 0 {
		// Only time.
		return t.Format("15:04:05"), nil
	}

	return t.Time, nil
}

```
the pr can Fixes #2012

### CODE REVIEW

File: contrib/drivers/mysql/mysql_z_unit_issue_test.go [hunk 1]
```diff
@@ -431,6 +431,45 @@ func Test_Issue1733(t *testing.T) {
 	})
 }
 
+// https://github.com/gogf/gf/issues/2102
+func Test_Issue2012(t *testing.T) {
```
Comment (gqcn) [inline contrib/drivers/mysql/mysql_z_unit_issue_test.go:435]: Invalid issue id `2102` in comment, which might be `https://github.com/gogf/gf/issues/2012`.

**Comment by cyjaysong** [comment]
看看我这种方案如何
https://github.com/gogf/gf/pull/3712

**Review by gqcn — APPROVED** [review]
