### PR TITLE
fix(database/gdb): handle empty string in Fields() gracefully

### LINKED ISSUE #4697: database/gdb: Fields with empty string generates invalid SQL
## Go version
go version go1.25.0 linux/amd64

## GoFrame version
v2 (master branch, commit sha: latest)

## Can this bug be reproduced with the latest release?
Option Yes

## What did you do?
Called `Fields("")` with an empty string on a database Model:

```go
result, err := db.Model(table).Fields("").Limit(1).All()
```

**Test case reference:** `Test_Model_Fields_Empty` in PR #4703

## What did you see happen?
The framework generated invalid SQL with missing field list:

```sql
SELECT  FROM `user_1770956455090062620` LIMIT 1
       ^^ Missing fields here
```

SQL execution error:
```
Error 1064 (42000): You have an error in your SQL syntax ... near 'FROM `user_1770956455090062620` LIMIT 1'
```

## What did you expect to see?
Empty string in Fields should either:
- **Option A (Recommended):** Be ignored (equivalent to not calling Fields), selecting all fields: `SELECT * FROM ...`
- **Option B:** Return a clear parameter validation error

## Additional Context
- **Parent issue:** #4689 (comprehensive database driver test coverage)
- **Discovered in:** PR #4703 while adding pagination and error handling tests
- **Affected drivers:** All database drivers (MySQL, PostgreSQL, etc.)
- **Regression test:** Added in PR #4703 to prevent recurrence after fix

### PR DESCRIPTION
**Pull request by lingcoder**
## Summary
Fix bug where `Fields("")` with empty string generates invalid SQL `SELECT FROM table`.

## Root Cause
`mappingAndFilterToTableFields` method doesn't skip empty strings when processing fields:
- `gstr.SplitAndTrim("", ",")` returns empty array
- No fields added to query
- Results in invalid SQL: `SELECT FROM table`

## Fix
Skip empty string fields in `mappingAndFilterToTableFields` (line 97-100):
```go
// Skip empty string fields
if fieldStr == "" {
    continue
}
```

## Behavior Changes
- `Fields("")` → SELECT * FROM table (uses default)
- `Fields("", "id")` → SELECT id FROM table (ignores empty string)
- `Fields("id", "", "nickname")` → SELECT id, nickname FROM table

## Tests
Added `Test_Issue4697` with 3 scenarios covering all cases above.

## Related
Fixes #4697
Ref #4703 (discovered during pagination test development)

### CODE REVIEW

**Comment by lingcoder** [comment]
已调整

File: database/gdb/gdb_model_utility.go [hunk 1]
```diff
@@ -94,6 +94,10 @@ func (m *Model) mappingAndFilterToTableFields(table string, fields []any, filter
 			fieldStr         = gconv.String(field)
 			inputFieldsArray []string
 		)
+		// Skip empty string fields
+		if fieldStr == "" {
```
Comment (gqcn) [inline database/gdb/gdb_model_utility.go]: 是否在`Fields`方法那里过滤下空字符串即可？

Comment (lingcoder) [reply database/gdb/gdb_model_utility.go]: mappingAndFilterToTableFields 是 Fields/FieldsEx/FieldsPrefix 的共同底层路径，在这里过滤一次即可覆盖所有入口，避免在每个方法中重复过滤逻辑。如果放在 Fields()入口层，由于参数是 ...any（混合 string/struct/map），需要额外的类型断言和循环过滤，代码量反而更多。
