### PR TITLE
fix issue 2403

### LINKED ISSUE #2403: gdb使用结构查询，包含gjson.Json字段且为nil时，也会作为空字符串条件查询
gf v2.3.0

### 示例代码
```go
func main() {                                    
    type where struct {                          
        g.Meta `orm:"table:test_json, do:true"`
        ID   int                                 
        Data *gjson.Json                         
    }                                            
                                                 
    ctx := gctx.New()                            
                                                 
    query := where{                              
        ID: 1,                                   
    }                                            
                                                 
    g.DB().Model("test_json").Ctx(ctx).One(query)
}                                                
```

### 期望SQL
```sql
SELECT * FROM "test_json" WHERE "id"=1 LIMIT 1
```

### 实际执行SQL
```sql
SELECT * FROM "test_json" WHERE "id"=1 AND "data"='' LIMIT 1
```

### PR DESCRIPTION
**Pull request by qinyuguang**
fix #2403

### CODE REVIEW

File: database/gdb/gdb_func.go [hunk 1]
```diff
@@ -210,7 +211,7 @@ func DataToMapDeep(value interface{}) map[string]interface{} {
 	m := gconv.Map(value, structTagPriority...)
 	for k, v := range m {
 		switch v.(type) {
-		case time.Time, *time.Time, gtime.Time, *gtime.Time:
+		case time.Time, *time.Time, gtime.Time, *gtime.Time, gjson.Json, *gjson.Json:
```
Comment (gqcn) [inline database/gdb/gdb_func.go:214]: Please add associated unit testing case for this case.

**Review by gqcn — CHANGES_REQUESTED** [review]

File: database/gdb/gdb_func.go (hunk 1 above)
Comment (qinyuguang) [reply database/gdb/gdb_func.go:214]: done

**Review by gqcn — APPROVED** [review]
